version: '3.8'

services:

  # NOTRE APPLICATION (DEEP INSIDE US)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:80" # Expose le port 80 du conteneur sur le port 81 de l'hôte
    networks:
      - monitoring

  # SERVICE NGINX PROMETHEUS EXPORTER
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    ports:
      - "9113:9113"
    command:
      - "--nginx.scrape-uri=http://app:80/stub_status" # Commande correcte pour spécifier l'URL du stub_status
    depends_on:
      - app
    networks:
      - monitoring
      
  # SERVICE NODE EXPORTER
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100" # Expose le port 9100 pour les métriques Node Exporter
    networks:
      - monitoring

  # SERVICE PROMETHEUS
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Configuration de Prometheus

  # SERVICE GRAFANA :
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Mot de passe admin pour Grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning  # Monter la configuration du provisioning
      - grafana_data:/var/lib/grafana  # Volumes persistants pour les données de Grafana
    depends_on:
      - prometheus
    restart: always
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  grafana_data:

