apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # L'adresse du service Prometheus dans Docker
    isDefault: true
    editable: true
